# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GITROOT\jg_MayaLightingTool\lightingTool\designer\lightingTool_form.ui'
#
# Created: Sat Jun 13 23:22:03 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LightManagerForm(object):
    def setupUi(self, LightManagerForm):
        LightManagerForm.setObjectName("LightManagerForm")
        LightManagerForm.resize(1055, 655)
        LightManagerForm.setMinimumSize(QtCore.QSize(1055, 400))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(LightManagerForm)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabMain = QtGui.QTabWidget(LightManagerForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMain.sizePolicy().hasHeightForWidth())
        self.tabMain.setSizePolicy(sizePolicy)
        self.tabMain.setMovable(True)
        self.tabMain.setObjectName("tabMain")
        self.tabLights = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabLights.sizePolicy().hasHeightForWidth())
        self.tabLights.setSizePolicy(sizePolicy)
        self.tabLights.setObjectName("tabLights")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tabLights)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.wgTabLights = QtGui.QWidget(self.tabLights)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgTabLights.sizePolicy().hasHeightForWidth())
        self.wgTabLights.setSizePolicy(sizePolicy)
        self.wgTabLights.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wgTabLights.setAutoFillBackground(False)
        self.wgTabLights.setObjectName("wgTabLights")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.wgTabLights)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.wgMain = QtGui.QWidget(self.wgTabLights)
        self.wgMain.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgMain.sizePolicy().hasHeightForWidth())
        self.wgMain.setSizePolicy(sizePolicy)
        self.wgMain.setMaximumSize(QtCore.QSize(780, 16777215))
        self.wgMain.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wgMain.setObjectName("wgMain")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.wgMain)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frLayer = QtGui.QFrame(self.wgMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frLayer.sizePolicy().hasHeightForWidth())
        self.frLayer.setSizePolicy(sizePolicy)
        self.frLayer.setMinimumSize(QtCore.QSize(0, 30))
        self.frLayer.setMaximumSize(QtCore.QSize(780, 60))
        self.frLayer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frLayer.setStyleSheet("")
        self.frLayer.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frLayer.setFrameShadow(QtGui.QFrame.Raised)
        self.frLayer.setObjectName("frLayer")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frLayer)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layoutLayer = QtGui.QHBoxLayout()
        self.layoutLayer.setSpacing(0)
        self.layoutLayer.setContentsMargins(0, 0, 0, 0)
        self.layoutLayer.setObjectName("layoutLayer")
        self.lblActive = QtGui.QLabel(self.frLayer)
        self.lblActive.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActive.sizePolicy().hasHeightForWidth())
        self.lblActive.setSizePolicy(sizePolicy)
        self.lblActive.setMinimumSize(QtCore.QSize(110, 0))
        self.lblActive.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lblActive.setSizeIncrement(QtCore.QSize(0, 0))
        self.lblActive.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lblActive.setFont(font)
        self.lblActive.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblActive.setObjectName("lblActive")
        self.layoutLayer.addWidget(self.lblActive)
        self.lblRenderLayer = QtGui.QLabel(self.frLayer)
        self.lblRenderLayer.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRenderLayer.sizePolicy().hasHeightForWidth())
        self.lblRenderLayer.setSizePolicy(sizePolicy)
        self.lblRenderLayer.setMinimumSize(QtCore.QSize(100, 0))
        self.lblRenderLayer.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblRenderLayer.setSizeIncrement(QtCore.QSize(0, 0))
        self.lblRenderLayer.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.lblRenderLayer.setFont(font)
        self.lblRenderLayer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblRenderLayer.setObjectName("lblRenderLayer")
        self.layoutLayer.addWidget(self.lblRenderLayer)
        self.cbLayers = QtGui.QComboBox(self.frLayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbLayers.sizePolicy().hasHeightForWidth())
        self.cbLayers.setSizePolicy(sizePolicy)
        self.cbLayers.setMinimumSize(QtCore.QSize(200, 0))
        self.cbLayers.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cbLayers.setObjectName("cbLayers")
        self.layoutLayer.addWidget(self.cbLayers)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutLayer.addItem(spacerItem)
        self.frame = QtGui.QFrame(self.frLayer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cbxRefresh = QtGui.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.cbxRefresh.setFont(font)
        self.cbxRefresh.setChecked(True)
        self.cbxRefresh.setObjectName("cbxRefresh")
        self.horizontalLayout_10.addWidget(self.cbxRefresh)
        self.btnRefresh = QtGui.QPushButton(self.frame)
        self.btnRefresh.setEnabled(False)
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_10.addWidget(self.btnRefresh)
        self.layoutLayer.addWidget(self.frame)
        self.horizontalLayout_3.addLayout(self.layoutLayer)
        self.verticalLayout_4.addWidget(self.frLayer)
        self.lineLayer = QtGui.QFrame(self.wgMain)
        self.lineLayer.setFrameShape(QtGui.QFrame.HLine)
        self.lineLayer.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineLayer.setObjectName("lineLayer")
        self.verticalLayout_4.addWidget(self.lineLayer)
        self.frActive = QtGui.QFrame(self.wgMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frActive.sizePolicy().hasHeightForWidth())
        self.frActive.setSizePolicy(sizePolicy)
        self.frActive.setMinimumSize(QtCore.QSize(780, 0))
        self.frActive.setMaximumSize(QtCore.QSize(780, 16777215))
        self.frActive.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frActive.setAutoFillBackground(True)
        self.frActive.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frActive.setFrameShadow(QtGui.QFrame.Sunken)
        self.frActive.setObjectName("frActive")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frActive)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrActive = QtGui.QScrollArea(self.frActive)
        self.scrActive.setStyleSheet("")
        self.scrActive.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrActive.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrActive.setWidgetResizable(True)
        self.scrActive.setObjectName("scrActive")
        self.scrlyActive = QtGui.QWidget()
        self.scrlyActive.setGeometry(QtCore.QRect(0, 0, 741, 467))
        self.scrlyActive.setObjectName("scrlyActive")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrlyActive)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lyActive = QtGui.QVBoxLayout()
        self.lyActive.setContentsMargins(4, 4, 4, 4)
        self.lyActive.setObjectName("lyActive")
        self.verticalLayout.addLayout(self.lyActive)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.scrActive.setWidget(self.scrlyActive)
        self.horizontalLayout_5.addWidget(self.scrActive)
        self.verticalLayout_4.addWidget(self.frActive)
        self.frPresets = QtGui.QFrame(self.wgMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frPresets.sizePolicy().hasHeightForWidth())
        self.frPresets.setSizePolicy(sizePolicy)
        self.frPresets.setMinimumSize(QtCore.QSize(740, 5))
        self.frPresets.setMaximumSize(QtCore.QSize(780, 16777215))
        self.frPresets.setBaseSize(QtCore.QSize(0, 0))
        self.frPresets.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frPresets.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"selection-color: rgb(207, 207, 207);\n"
"selection-background-color: rgb(207, 207, 207);")
        self.frPresets.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frPresets.setFrameShadow(QtGui.QFrame.Sunken)
        self.frPresets.setObjectName("frPresets")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frPresets)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lyPresets = QtGui.QHBoxLayout()
        self.lyPresets.setObjectName("lyPresets")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.lyPresets.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.lyPresets)
        self.verticalLayout_4.addWidget(self.frPresets)
        self.horizontalLayout_4.addWidget(self.wgMain)
        self.tabSide = QtGui.QTabWidget(self.wgTabLights)
        self.tabSide.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSide.sizePolicy().hasHeightForWidth())
        self.tabSide.setSizePolicy(sizePolicy)
        self.tabSide.setMaximumSize(QtCore.QSize(1111111, 16777215))
        font = QtGui.QFont()
        self.tabSide.setFont(font)
        self.tabSide.setCursor(QtCore.Qt.ArrowCursor)
        self.tabSide.setMouseTracking(False)
        self.tabSide.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabSide.setAcceptDrops(False)
        self.tabSide.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabSide.setAutoFillBackground(False)
        self.tabSide.setStyleSheet("")
        self.tabSide.setTabPosition(QtGui.QTabWidget.North)
        self.tabSide.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabSide.setIconSize(QtCore.QSize(16, 16))
        self.tabSide.setElideMode(QtCore.Qt.ElideNone)
        self.tabSide.setUsesScrollButtons(True)
        self.tabSide.setTabsClosable(False)
        self.tabSide.setMovable(True)
        self.tabSide.setObjectName("tabSide")
        self.tabOutliner = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabOutliner.sizePolicy().hasHeightForWidth())
        self.tabOutliner.setSizePolicy(sizePolicy)
        self.tabOutliner.setObjectName("tabOutliner")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tabOutliner)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.wgOutliner = QtGui.QWidget(self.tabOutliner)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgOutliner.sizePolicy().hasHeightForWidth())
        self.wgOutliner.setSizePolicy(sizePolicy)
        self.wgOutliner.setMinimumSize(QtCore.QSize(195, 0))
        self.wgOutliner.setMaximumSize(QtCore.QSize(111111, 16777215))
        self.wgOutliner.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wgOutliner.setAutoFillBackground(True)
        self.wgOutliner.setObjectName("wgOutliner")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wgOutliner)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 1, 0, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.trOutliner = QtGui.QTreeWidget(self.wgOutliner)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trOutliner.sizePolicy().hasHeightForWidth())
        self.trOutliner.setSizePolicy(sizePolicy)
        self.trOutliner.setMinimumSize(QtCore.QSize(170, 0))
        self.trOutliner.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.trOutliner.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.trOutliner.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.trOutliner.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.trOutliner.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.trOutliner.setObjectName("trOutliner")
        self.verticalLayout_2.addWidget(self.trOutliner)
        self.frLayerBtns = QtGui.QFrame(self.wgOutliner)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frLayerBtns.sizePolicy().hasHeightForWidth())
        self.frLayerBtns.setSizePolicy(sizePolicy)
        self.frLayerBtns.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frLayerBtns.setSizeIncrement(QtCore.QSize(0, 0))
        self.frLayerBtns.setAutoFillBackground(True)
        self.frLayerBtns.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frLayerBtns.setFrameShadow(QtGui.QFrame.Raised)
        self.frLayerBtns.setObjectName("frLayerBtns")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frLayerBtns)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAddLayer = QtGui.QPushButton(self.frLayerBtns)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 100, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 100, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 100, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnAddLayer.setPalette(palette)
        self.btnAddLayer.setObjectName("btnAddLayer")
        self.horizontalLayout_2.addWidget(self.btnAddLayer)
        self.btnRemoveLayer = QtGui.QPushButton(self.frLayerBtns)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnRemoveLayer.setPalette(palette)
        self.btnRemoveLayer.setObjectName("btnRemoveLayer")
        self.horizontalLayout_2.addWidget(self.btnRemoveLayer)
        self.verticalLayout_2.addWidget(self.frLayerBtns)
        self.verticalLayout_9.addWidget(self.wgOutliner)
        self.tabSide.addTab(self.tabOutliner, "")
        self.tabAttr = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabAttr.sizePolicy().hasHeightForWidth())
        self.tabAttr.setSizePolicy(sizePolicy)
        self.tabAttr.setObjectName("tabAttr")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tabAttr)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lblAttr = QtGui.QLabel(self.tabAttr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAttr.sizePolicy().hasHeightForWidth())
        self.lblAttr.setSizePolicy(sizePolicy)
        self.lblAttr.setMinimumSize(QtCore.QSize(205, 25))
        self.lblAttr.setMaximumSize(QtCore.QSize(16777215, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lblAttr.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.lblAttr.setFont(font)
        self.lblAttr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblAttr.setAutoFillBackground(True)
        self.lblAttr.setFrameShape(QtGui.QFrame.Box)
        self.lblAttr.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAttr.setText("")
        self.lblAttr.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAttr.setObjectName("lblAttr")
        self.verticalLayout_10.addWidget(self.lblAttr)
        self.scrAttr = QtGui.QScrollArea(self.tabAttr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrAttr.sizePolicy().hasHeightForWidth())
        self.scrAttr.setSizePolicy(sizePolicy)
        self.scrAttr.setMinimumSize(QtCore.QSize(205, 420))
        self.scrAttr.setMaximumSize(QtCore.QSize(195, 16777215))
        self.scrAttr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrAttr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrAttr.setWidgetResizable(True)
        self.scrAttr.setObjectName("scrAttr")
        self.scrlyAttr = QtGui.QWidget()
        self.scrlyAttr.setGeometry(QtCore.QRect(0, 0, 186, 418))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrlyAttr.sizePolicy().hasHeightForWidth())
        self.scrlyAttr.setSizePolicy(sizePolicy)
        self.scrlyAttr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrlyAttr.setObjectName("scrlyAttr")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrlyAttr)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.wgAtrTop = QtGui.QWidget(self.scrlyAttr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgAtrTop.sizePolicy().hasHeightForWidth())
        self.wgAtrTop.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.wgAtrTop.setPalette(palette)
        self.wgAtrTop.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.wgAtrTop.setObjectName("wgAtrTop")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.wgAtrTop)
        self.verticalLayout_12.setContentsMargins(2, 4, 2, 4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_5.addWidget(self.wgAtrTop)
        self.wgAttrBot = QtGui.QWidget(self.scrlyAttr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgAttrBot.sizePolicy().hasHeightForWidth())
        self.wgAttrBot.setSizePolicy(sizePolicy)
        self.wgAttrBot.setMinimumSize(QtCore.QSize(0, 350))
        self.wgAttrBot.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wgAttrBot.setObjectName("wgAttrBot")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.wgAttrBot)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lyAttr = QtGui.QVBoxLayout()
        self.lyAttr.setObjectName("lyAttr")
        self.verticalLayout_13.addLayout(self.lyAttr)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.wgAttrBot)
        self.scrAttr.setWidget(self.scrlyAttr)
        self.verticalLayout_10.addWidget(self.scrAttr)
        self.tabSide.addTab(self.tabAttr, "")
        self.tabLayers = QtGui.QWidget()
        self.tabLayers.setObjectName("tabLayers")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.tabLayers)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lblLayers = QtGui.QLabel(self.tabLayers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLayers.sizePolicy().hasHeightForWidth())
        self.lblLayers.setSizePolicy(sizePolicy)
        self.lblLayers.setMinimumSize(QtCore.QSize(0, 25))
        self.lblLayers.setMaximumSize(QtCore.QSize(16777215, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lblLayers.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.lblLayers.setFont(font)
        self.lblLayers.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblLayers.setAutoFillBackground(True)
        self.lblLayers.setFrameShape(QtGui.QFrame.Box)
        self.lblLayers.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblLayers.setText("")
        self.lblLayers.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLayers.setObjectName("lblLayers")
        self.verticalLayout_17.addWidget(self.lblLayers)
        self.scrLayers = QtGui.QScrollArea(self.tabLayers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrLayers.sizePolicy().hasHeightForWidth())
        self.scrLayers.setSizePolicy(sizePolicy)
        self.scrLayers.setMinimumSize(QtCore.QSize(195, 420))
        self.scrLayers.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrLayers.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrLayers.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrLayers.setWidgetResizable(True)
        self.scrLayers.setObjectName("scrLayers")
        self.scrlyLayers = QtGui.QWidget()
        self.scrlyLayers.setGeometry(QtCore.QRect(0, 0, 186, 516))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrlyLayers.sizePolicy().hasHeightForWidth())
        self.scrlyLayers.setSizePolicy(sizePolicy)
        self.scrlyLayers.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrlyLayers.setObjectName("scrlyLayers")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.scrlyLayers)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem4)
        self.scrLayers.setWidget(self.scrlyLayers)
        self.verticalLayout_17.addWidget(self.scrLayers)
        self.tabSide.addTab(self.tabLayers, "")
        self.horizontalLayout_4.addWidget(self.tabSide)
        self.verticalLayout_8.addWidget(self.wgTabLights)
        self.tabMain.addTab(self.tabLights, "")
        self.tabHdr = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabHdr.sizePolicy().hasHeightForWidth())
        self.tabHdr.setSizePolicy(sizePolicy)
        self.tabHdr.setObjectName("tabHdr")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tabHdr)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.wgTabHDR = QtGui.QWidget(self.tabHdr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgTabHDR.sizePolicy().hasHeightForWidth())
        self.wgTabHDR.setSizePolicy(sizePolicy)
        self.wgTabHDR.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.wgTabHDR.setAutoFillBackground(False)
        self.wgTabHDR.setObjectName("wgTabHDR")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.wgTabHDR)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frHdr = QtGui.QFrame(self.wgTabHDR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frHdr.sizePolicy().hasHeightForWidth())
        self.frHdr.setSizePolicy(sizePolicy)
        self.frHdr.setMinimumSize(QtCore.QSize(0, 0))
        self.frHdr.setMaximumSize(QtCore.QSize(1111111, 16777215))
        self.frHdr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frHdr.setAutoFillBackground(True)
        self.frHdr.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frHdr.setFrameShadow(QtGui.QFrame.Sunken)
        self.frHdr.setObjectName("frHdr")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frHdr)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scrHdr = QtGui.QScrollArea(self.frHdr)
        self.scrHdr.setStyleSheet("")
        self.scrHdr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrHdr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrHdr.setWidgetResizable(True)
        self.scrHdr.setObjectName("scrHdr")
        self.scrlyHdr = QtGui.QWidget()
        self.scrlyHdr.setGeometry(QtCore.QRect(0, 0, 589, 522))
        self.scrlyHdr.setObjectName("scrlyHdr")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.scrlyHdr)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lyHdr = QtGui.QVBoxLayout()
        self.lyHdr.setContentsMargins(4, 4, 4, 4)
        self.lyHdr.setObjectName("lyHdr")
        self.verticalLayout_7.addLayout(self.lyHdr)
        self.scrHdr.setWidget(self.scrlyHdr)
        self.horizontalLayout_8.addWidget(self.scrHdr)
        self.horizontalLayout_7.addWidget(self.frHdr)
        self.frLoad = QtGui.QFrame(self.wgTabHDR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frLoad.sizePolicy().hasHeightForWidth())
        self.frLoad.setSizePolicy(sizePolicy)
        self.frLoad.setMinimumSize(QtCore.QSize(0, 500))
        self.frLoad.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frLoad.setFrameShape(QtGui.QFrame.Box)
        self.frLoad.setFrameShadow(QtGui.QFrame.Raised)
        self.frLoad.setObjectName("frLoad")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frLoad)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lyLoad = QtGui.QVBoxLayout()
        self.lyLoad.setContentsMargins(4, -1, 4, -1)
        self.lyLoad.setObjectName("lyLoad")
        self.btnImage = QtGui.QPushButton(self.frLoad)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImage.sizePolicy().hasHeightForWidth())
        self.btnImage.setSizePolicy(sizePolicy)
        self.btnImage.setMinimumSize(QtCore.QSize(320, 160))
        self.btnImage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnImage.setText("")
        self.btnImage.setObjectName("btnImage")
        self.lyLoad.addWidget(self.btnImage)
        self.btnExplore = QtGui.QPushButton(self.frLoad)
        self.btnExplore.setObjectName("btnExplore")
        self.lyLoad.addWidget(self.btnExplore)
        self.frInfo = QtGui.QFrame(self.frLoad)
        self.frInfo.setFrameShape(QtGui.QFrame.Box)
        self.frInfo.setFrameShadow(QtGui.QFrame.Sunken)
        self.frInfo.setObjectName("frInfo")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frInfo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lyFileName = QtGui.QHBoxLayout()
        self.lyFileName.setObjectName("lyFileName")
        self.lblFileName = QtGui.QLineEdit(self.frInfo)
        self.lblFileName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFileName.sizePolicy().hasHeightForWidth())
        self.lblFileName.setSizePolicy(sizePolicy)
        self.lblFileName.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblFileName.setFont(font)
        self.lblFileName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFileName.setReadOnly(True)
        self.lblFileName.setObjectName("lblFileName")
        self.lyFileName.addWidget(self.lblFileName)
        self.leFileName = QtGui.QLineEdit(self.frInfo)
        self.leFileName.setEnabled(False)
        self.leFileName.setReadOnly(True)
        self.leFileName.setObjectName("leFileName")
        self.lyFileName.addWidget(self.leFileName)
        self.verticalLayout_3.addLayout(self.lyFileName)
        self.lyDocType = QtGui.QHBoxLayout()
        self.lyDocType.setObjectName("lyDocType")
        self.lblDocType = QtGui.QLineEdit(self.frInfo)
        self.lblDocType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDocType.sizePolicy().hasHeightForWidth())
        self.lblDocType.setSizePolicy(sizePolicy)
        self.lblDocType.setMinimumSize(QtCore.QSize(80, 0))
        self.lblDocType.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblDocType.setFont(font)
        self.lblDocType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDocType.setReadOnly(True)
        self.lblDocType.setObjectName("lblDocType")
        self.lyDocType.addWidget(self.lblDocType)
        self.leDocTYpe = QtGui.QLineEdit(self.frInfo)
        self.leDocTYpe.setEnabled(False)
        self.leDocTYpe.setReadOnly(True)
        self.leDocTYpe.setObjectName("leDocTYpe")
        self.lyDocType.addWidget(self.leDocTYpe)
        self.verticalLayout_3.addLayout(self.lyDocType)
        self.lyDateCreated = QtGui.QHBoxLayout()
        self.lyDateCreated.setObjectName("lyDateCreated")
        self.lblDateCreated = QtGui.QLineEdit(self.frInfo)
        self.lblDateCreated.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateCreated.sizePolicy().hasHeightForWidth())
        self.lblDateCreated.setSizePolicy(sizePolicy)
        self.lblDateCreated.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblDateCreated.setFont(font)
        self.lblDateCreated.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDateCreated.setReadOnly(True)
        self.lblDateCreated.setObjectName("lblDateCreated")
        self.lyDateCreated.addWidget(self.lblDateCreated)
        self.leDateCreated = QtGui.QLineEdit(self.frInfo)
        self.leDateCreated.setEnabled(False)
        self.leDateCreated.setReadOnly(True)
        self.leDateCreated.setObjectName("leDateCreated")
        self.lyDateCreated.addWidget(self.leDateCreated)
        self.verticalLayout_3.addLayout(self.lyDateCreated)
        self.lyDateMod = QtGui.QHBoxLayout()
        self.lyDateMod.setObjectName("lyDateMod")
        self.lblDateMod = QtGui.QLineEdit(self.frInfo)
        self.lblDateMod.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDateMod.sizePolicy().hasHeightForWidth())
        self.lblDateMod.setSizePolicy(sizePolicy)
        self.lblDateMod.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblDateMod.setFont(font)
        self.lblDateMod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDateMod.setReadOnly(True)
        self.lblDateMod.setObjectName("lblDateMod")
        self.lyDateMod.addWidget(self.lblDateMod)
        self.leDateMod = QtGui.QLineEdit(self.frInfo)
        self.leDateMod.setEnabled(False)
        self.leDateMod.setReadOnly(True)
        self.leDateMod.setObjectName("leDateMod")
        self.lyDateMod.addWidget(self.leDateMod)
        self.verticalLayout_3.addLayout(self.lyDateMod)
        self.lyFileSize = QtGui.QHBoxLayout()
        self.lyFileSize.setObjectName("lyFileSize")
        self.lblFileSize = QtGui.QLineEdit(self.frInfo)
        self.lblFileSize.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFileSize.sizePolicy().hasHeightForWidth())
        self.lblFileSize.setSizePolicy(sizePolicy)
        self.lblFileSize.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblFileSize.setFont(font)
        self.lblFileSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFileSize.setReadOnly(True)
        self.lblFileSize.setObjectName("lblFileSize")
        self.lyFileSize.addWidget(self.lblFileSize)
        self.leFileSize = QtGui.QLineEdit(self.frInfo)
        self.leFileSize.setEnabled(False)
        self.leFileSize.setReadOnly(True)
        self.leFileSize.setObjectName("leFileSize")
        self.lyFileSize.addWidget(self.leFileSize)
        self.verticalLayout_3.addLayout(self.lyFileSize)
        self.lyResolution = QtGui.QHBoxLayout()
        self.lyResolution.setObjectName("lyResolution")
        self.lblResolution = QtGui.QLineEdit(self.frInfo)
        self.lblResolution.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResolution.sizePolicy().hasHeightForWidth())
        self.lblResolution.setSizePolicy(sizePolicy)
        self.lblResolution.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblResolution.setFont(font)
        self.lblResolution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblResolution.setReadOnly(True)
        self.lblResolution.setObjectName("lblResolution")
        self.lyResolution.addWidget(self.lblResolution)
        self.leResolution = QtGui.QLineEdit(self.frInfo)
        self.leResolution.setEnabled(False)
        self.leResolution.setReadOnly(True)
        self.leResolution.setObjectName("leResolution")
        self.lyResolution.addWidget(self.leResolution)
        self.verticalLayout_3.addLayout(self.lyResolution)
        self.lyLoad.addWidget(self.frInfo)
        self.line_LoadPresetTop = QtGui.QFrame(self.frLoad)
        self.line_LoadPresetTop.setFrameShape(QtGui.QFrame.HLine)
        self.line_LoadPresetTop.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_LoadPresetTop.setObjectName("line_LoadPresetTop")
        self.lyLoad.addWidget(self.line_LoadPresetTop)
        self.groupLoad = QtGui.QGroupBox(self.frLoad)
        self.groupLoad.setTitle("")
        self.groupLoad.setObjectName("groupLoad")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupLoad)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btnLoad = QtGui.QPushButton(self.groupLoad)
        self.btnLoad.setEnabled(False)
        self.btnLoad.setMinimumSize(QtCore.QSize(0, 40))
        self.btnLoad.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btnLoad.setObjectName("btnLoad")
        self.verticalLayout_14.addWidget(self.btnLoad)
        self.lyLoadPreset = QtGui.QHBoxLayout()
        self.lyLoadPreset.setObjectName("lyLoadPreset")
        self.lblLoadPresetLabel = QtGui.QLabel(self.groupLoad)
        self.lblLoadPresetLabel.setObjectName("lblLoadPresetLabel")
        self.lyLoadPreset.addWidget(self.lblLoadPresetLabel)
        self.cbLoadPreset = QtGui.QComboBox(self.groupLoad)
        self.cbLoadPreset.setObjectName("cbLoadPreset")
        self.lyLoadPreset.addWidget(self.cbLoadPreset)
        self.verticalLayout_14.addLayout(self.lyLoadPreset)
        self.lyLoad.addWidget(self.groupLoad)
        self.line_LoadPresetBot = QtGui.QFrame(self.frLoad)
        self.line_LoadPresetBot.setFrameShape(QtGui.QFrame.HLine)
        self.line_LoadPresetBot.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_LoadPresetBot.setObjectName("line_LoadPresetBot")
        self.lyLoad.addWidget(self.line_LoadPresetBot)
        self.btnRefreshHdr = QtGui.QPushButton(self.frLoad)
        self.btnRefreshHdr.setObjectName("btnRefreshHdr")
        self.lyLoad.addWidget(self.btnRefreshHdr)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.lyLoad.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.lyLoad)
        self.horizontalLayout_7.addWidget(self.frLoad)
        self.verticalLayout_11.addWidget(self.wgTabHDR)
        self.frPath = QtGui.QFrame(self.tabHdr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frPath.sizePolicy().hasHeightForWidth())
        self.frPath.setSizePolicy(sizePolicy)
        self.frPath.setMinimumSize(QtCore.QSize(1000, 25))
        self.frPath.setMaximumSize(QtCore.QSize(16777215, 1111111))
        self.frPath.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frPath.setFrameShadow(QtGui.QFrame.Raised)
        self.frPath.setObjectName("frPath")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frPath)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblPath = QtGui.QLabel(self.frPath)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPath.sizePolicy().hasHeightForWidth())
        self.lblPath.setSizePolicy(sizePolicy)
        self.lblPath.setMinimumSize(QtCore.QSize(100, 0))
        self.lblPath.setObjectName("lblPath")
        self.horizontalLayout_9.addWidget(self.lblPath)
        self.lePath = QtGui.QLineEdit(self.frPath)
        self.lePath.setObjectName("lePath")
        self.horizontalLayout_9.addWidget(self.lePath)
        self.btnPathExplore = QtGui.QPushButton(self.frPath)
        self.btnPathExplore.setMinimumSize(QtCore.QSize(0, 0))
        self.btnPathExplore.setObjectName("btnPathExplore")
        self.horizontalLayout_9.addWidget(self.btnPathExplore)
        self.verticalLayout_11.addWidget(self.frPath)
        self.tabMain.addTab(self.tabHdr, "")
        self.horizontalLayout_6.addWidget(self.tabMain)

        self.retranslateUi(LightManagerForm)
        self.tabMain.setCurrentIndex(1)
        self.tabSide.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(LightManagerForm)

    def retranslateUi(self, LightManagerForm):
        LightManagerForm.setWindowTitle(QtGui.QApplication.translate("LightManagerForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lblActive.setText(QtGui.QApplication.translate("LightManagerForm", "ACTIVE LIGHTS: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRenderLayer.setText(QtGui.QApplication.translate("LightManagerForm", " Render Layer -   ", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxRefresh.setText(QtGui.QApplication.translate("LightManagerForm", "Auto Refresh UI (on mouse Over)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRefresh.setText(QtGui.QApplication.translate("LightManagerForm", "REFRESH", None, QtGui.QApplication.UnicodeUTF8))
        self.trOutliner.headerItem().setText(0, QtGui.QApplication.translate("LightManagerForm", "SCENE LIGHTS", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddLayer.setText(QtGui.QApplication.translate("LightManagerForm", "ADD TO LAYER", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveLayer.setText(QtGui.QApplication.translate("LightManagerForm", "REMOVE", None, QtGui.QApplication.UnicodeUTF8))
        self.tabSide.setTabText(self.tabSide.indexOf(self.tabOutliner), QtGui.QApplication.translate("LightManagerForm", "OUTLINER", None, QtGui.QApplication.UnicodeUTF8))
        self.tabSide.setTabText(self.tabSide.indexOf(self.tabAttr), QtGui.QApplication.translate("LightManagerForm", "ATTRIBUTTES", None, QtGui.QApplication.UnicodeUTF8))
        self.tabSide.setTabText(self.tabSide.indexOf(self.tabLayers), QtGui.QApplication.translate("LightManagerForm", "LAYERS", None, QtGui.QApplication.UnicodeUTF8))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabLights), QtGui.QApplication.translate("LightManagerForm", "LIGHTS", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExplore.setText(QtGui.QApplication.translate("LightManagerForm", "Explore", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFileName.setText(QtGui.QApplication.translate("LightManagerForm", "File Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDocType.setText(QtGui.QApplication.translate("LightManagerForm", "Document Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDateCreated.setText(QtGui.QApplication.translate("LightManagerForm", "Date Created:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDateMod.setText(QtGui.QApplication.translate("LightManagerForm", "Date Modified", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFileSize.setText(QtGui.QApplication.translate("LightManagerForm", "File Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblResolution.setText(QtGui.QApplication.translate("LightManagerForm", "File Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoad.setText(QtGui.QApplication.translate("LightManagerForm", "LOAD FILE", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLoadPresetLabel.setText(QtGui.QApplication.translate("LightManagerForm", "Load Preset (or Selected Light):", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRefreshHdr.setText(QtGui.QApplication.translate("LightManagerForm", "Refresh Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPath.setText(QtGui.QApplication.translate("LightManagerForm", "  HDR Folder Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPathExplore.setText(QtGui.QApplication.translate("LightManagerForm", "Explore", None, QtGui.QApplication.UnicodeUTF8))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabHdr), QtGui.QApplication.translate("LightManagerForm", "HDRI", None, QtGui.QApplication.UnicodeUTF8))

